name: spfemenv
dependencies:
- alabaster=0.7.8=py27_0
- apptools=4.2.1=py27_0
- babel=2.3.3=py27_0
- backports=1.0=py27_0
- cairo=1.12.18=6
- configobj=5.0.6=py27_0
- coverage=4.2=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.10=py27_0
- docutils=0.12=py27_2
- envisage=4.4.0=py27_1
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- get_terminal_size=1.0.0=py27_0
- glib=2.43.0=1
- harfbuzz=0.9.39=1
- imagesize=0.7.1=py27_0
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_1
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- libpng=1.6.17=0
- libxml2=2.9.2=0
- markupsafe=0.23=py27_2
- matplotlib=1.4.3=np19py27_2
- mayavi=4.4.0=np19py27_0
- mkl=11.3.3=0
- mpmath=0.19=py27_1
- numpy=1.9.3=py27_3
- numpydoc=0.6.0=py27_0
- openssl=1.0.2h=1
- pango=1.39.0=1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.3=py27_0
- pip=8.1.2=py27_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py27_0
- ptyprocess=0.5.1=py27_0
- py2cairo=1.10.0=py27_2
- pycairo=1.10.0=py27_0
- pyface=4.4.0=py27_0
- pyflakes=1.3.0=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- qt=4.8.7=4
- readline=6.2=2
- scipy=0.17.1=np19py27_1
- setuptools=26.1.1=py27_0
- simplegeneric=0.8.1=py27_1
- sip=4.18=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx>=1.4.6=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- sqlite=3.13.0=0
- sympy=1.0=py27_0
- tk=8.5.18=0
- traitlets=4.2.2=py27_0
- traits=4.4.0=py27_0
- traitsui=4.4.0=py27_0
- vtk=5.10.1=py27_1
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- wxpython=3.0.0.0=py27_2
- zlib=1.2.8=3
- pip:
  - appdirs==1.4.0
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - meshpy==2016.1.2
  - prompt-toolkit==1.0.3
  - py==1.4.31
  - pytest==3.0.3
  - pytools==2016.2.2
  - sphinx-rtd-theme==0.1.9
  - wxpython-common==3.0.0.0

